# Generated by Django 6.0.1 on 2026-01-28 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Student',
        ),
    ]
